### ISSUE TITLE
CMakeLists.txt not found: vendors/realtek/boards/amebaZ2/CMakeLists.txt

### ISSUE THREAD

**Issue by hi-pablet** [ambiot/amazon-freertos#8]
Hi,

I’m trying to build the amazon-freertos project. I run the following commands:

echo "set(AFR_MANIFEST_BOARD_DIR \"boards\" CACHE INTERNAL \"\") > /vendors/manifest/manifest.cmake 
echo "set(AFR_MANIFEST_SUPPORTED_BOARDS \"amebaZ2\" CACHE INTERNAL \"\") >> /vendors/manifest/manifest.cmake 

mkdir build
cd build
cmake .. -DCMAKE_TOOLCHAIN_FILE=<path>/cmake-toolchain -DAFR_BOARD=realtek.amebaZ2
And I get the following error:

CMake Error at CMakeLists.txt:70 (include):
include could not find load file:

vendors/realtek/boards/amebaZ2/CMakeLists.txt

=========================Resolving dependencies==========================
CMake Error at tools/cmake/afr_utils.cmake:222 (message):
aws_demos is not a target.
Call Stack (most recent call first):
tools/cmake/afr_module.cmake:232 (afr_get_target_dependencies)
tools/cmake/afr_module.cmake:221 (__search_afr_dependencies_impl)
tools/cmake/afr_module.cmake:336 (__search_afr_dependencies)
CMakeLists.txt:110 (afr_resolve_dependencies)

– Configuring incomplete, errors occurred!

**Comment by hanksuu** [comment]
Hi,
The project only support IAR Embedded Workbench currently.
